### ISSUE TITLE
Can I deamonize launchfile and then access logs remotely without starting node? 

### ISSUE THREAD

**Issue by zentala** [xqms/rosmon#122]
`rosmon` is very convenient for debugging. But there is one feature that I am not sure how to set up or if it's even possible.  

I would like to set up some Linux services (daemons) that are starting my launch files with the system. I would execute `rosmon` with argument `--disable-ui` to get nice logs for `journalctl`. But then my question is: am I able to use `rosmon` on the remote machine, in order to read logs from the `rosmon` that is running on the robot with this fancy console UI?

I mean: 
* on the robot I am using rosmon that was executed as service with  `--disable-ui `
* on the remote machine I am connecting with those logs and print them with fancy console UI in order to speed up debugging

Is it even possible? 
How do you debug remotely processes that are starting automatically?

**Comment by xqms** [comment]
Here are the options I can think of:

 * Use `rqt_rosmon` and `rqt_console` to see node status and output of the remote nodes. I don't particularly like `rqt_console` myself, so I have written a replacement which looks more like a terminal. If there's interest in that, I can think about releasing it.
 * Start `rosmon` in a tmux/screen session. That way you can later log in and attach to the tmux session to see the terminal UI. Here are some pointers on how to do that:
https://forums.opensuse.org/showthread.php/506589-How-to-start-application-in-tmux-on-boot
https://gist.github.com/lionell/34c6d2bc58df11462fb73d034b2d21d1
Note that you usually have to tweak the tmux configuration to allow true color display.

I guess the second option fits your use case better. It also allows access to rosmon's debug facilities (coredumps / gdb launch).

I'm closing this since it's more of a question than an issue / wish. If you have a specific idea that would make rosmon better, feel free to reopen ;)
