### ISSUE TITLE
Can't upgrade to version 2.0.2

### ISSUE THREAD

**Issue by MichaelT64** [xqms/rosmon#87]
Hi
I have the version 1.0.10 and want to upgrade to version 2.0.2 and tried to update with
```
sudo apt-get update
sudo apt-get upgrade

```
but no update of rosmon appears.
Following the installation from the ROS wiki I get the following message:

> ros-kinetic-rosmon is already the newest version (1.0.10-0xenial-20190609-214009-0800).

So I have the newest version from the 1.0 path. Tried this with a Raspberry Pi and with a notebook with Ubuntu.
From my understanding of [ROS Index](https://index.ros.org/p/rosmon/github-xqms-rosmon/) I would expect that the 2.0.2 version is also available for kinetic.

**Comment by xqms** [comment]
Hey, thanks for the report. Indeed I did not release version 2.x for kinetic so far. I will do so in the next release cycle (probably next week). I currently have the problem that the CI pipeline is not working due to the recent security issues with the ROS buildfarm (https://discourse.ros.org/t/security-issue-on-ros-build-farm/9342).

I don't know how ROS Index works, but here are the repository status pages for kinetic and melodic, which report the version numbers accurately:

http://repositories.ros.org/status_page/ros_kinetic_default.html?q=rosmon
http://repositories.ros.org/status_page/ros_melodic_default.html?q=rosmon

**Comment by MichaelT64** [comment]
Hi
thanks, I did not know the  repository status pages (yet), but they seems to be of interest.
Is there a link to it from the ros.org or the wiki to it?

**Comment by xqms** [comment]
Well, this is more of a detail for package developers. It's mentioned in Dirk Thomas' presentation of the ROS buildfarm:
http://www.dirk-thomas.net/slides_roscon2016_ros-buildfarm/2016-10-09_roscon_ros-buildfarm.html#/5/6

If you want to improve the situation, consider raising an issue with ROS Index (they should maybe indicate the currently released version): https://github.com/ros-infrastructure/rosindex

**Comment by xqms** [comment]
I just released version 2.1.0 for melodic. As soon as the [kinetic sync hold](https://discourse.ros.org/t/preparing-for-kinetic-sync-2019-06-24/9663) is over, I'll perform a release for kinetic as well.

Would you be willing to test 2.1.0 on kinetic? I don't have any kinetic users here anymore, so I only have the CI tests to verify that we didn't break anything. An actual end-user test would be helpful ;-)

You could either compile rosmon yourself, or wait until the build farm has built Ubuntu packages (probably end of this week).

**Comment by MichaelT64** [comment]
Hi, I cloned rosmon and build it (after cloning rosfmt too) at the notebook and it seems to work.
But I have only simple launch files (I am just a hobbyist who plays a little bit with my robot and ROS in my free time), so I am not sure if everything works well.
It seems my Raspberry is overextended with building so I have to wait for the build farm.

Greetings
Michael

**Comment by matawed** [comment]
> I just released version 2.1.0 for melodic. 

When do you think will it be available in bionic ros repos, since [status page](http://repositories.ros.org/status_page/ros_melodic_default.html?q=rosmon) still reports a difference between `testing` and `main` for rosmon? 
[Package index](http://repositories.ros.org/ubuntu/main/dists/bionic/main/binary-amd64/Packages) for bionic still only provides 2.0.2.

**Comment by xqms** [comment]
When the next repo [sync](https://discourse.ros.org/t/preparing-for-melodic-sync-2019-06-28/9714) happens. This is done usually every 2-4 weeks and is manually initiated by the ROS maintainers. You can monitor the sync announcements here:
https://discourse.ros.org/c/release

**Comment by xqms** [comment]
In the meantime, if you want to beta-test (I'm always happy if we get more people doing this), you can switch your system to the shadow repository, which always contains the newest packages released by the package maintainers (i.e. me in this case):
http://wiki.ros.org/ShadowRepository

**Comment by MichaelT64** [comment]
At least I get catkin_make to build the sources at my Raspberry.
Everything seems to work (at least at my simple launch files).

**Comment by xqms** [comment]
Awesome, thanks for testing @MichaelT64 !

I'll trigger the release into Kinetic tomorrow.

**Comment by xqms** [comment]
Release PR for kinetic: https://github.com/ros/rosdistro/pull/21705
Will close this as soon as the PR is merged.

**Comment by xqms** [comment]
Packages for kinetic are out in the repositories.
